# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "avada sample sales pop"
client_id = "297b6bdc4d02e0eeaeca6ef8b051d1a4"
application_url = "https://outstanding-creativity-trinity-heating.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://outstanding-creativity-trinity-heating.trycloudflare.com/auth/shopify/callback",
  "https://outstanding-creativity-trinity-heating.trycloudflare.com/authSa/shopify/callback",
  "https://outstanding-creativity-trinity-heating.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "avada-tranning-t7-1.myshopify.com"
